/*ALTER TABLE [dbo].[ComunicadoCondominio]
    ADD CONSTRAINT [PK_ComunicadoCondominio] PRIMARY KEY CLUSTERED ([ComunicadoCondominioID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

