/*ALTER TABLE [dbo].[ComunicadoFicheiro]
    ADD CONSTRAINT [PK_ComunicadoFicheiro] PRIMARY KEY CLUSTERED ([ComunicadoFicheiroID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

