ALTER TABLE [dbo].[ExtratoSocial]
    ADD CONSTRAINT [PK_ExtratoSocial] PRIMARY KEY CLUSTERED ([ExtratoSocialID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

