ALTER TABLE [dbo].[FornecedorCategoria]
    ADD CONSTRAINT [PK_FornecedorCategoria] PRIMARY KEY CLUSTERED ([FornecedorCategoriaID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

