ALTER TABLE [dbo].[FornecedorKeyword]
    ADD CONSTRAINT [PK_FornecedorKeyword] PRIMARY KEY CLUSTERED ([FornecedorID] ASC, [Keyword] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

