ALTER TABLE [dbo].[FornecedorClassificacao]
    ADD CONSTRAINT [PK_FornecedorClassificacao] PRIMARY KEY CLUSTERED ([FornecedorClassificacaoID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

