ALTER TABLE [dbo].[FicheiroConteudo]
    ADD CONSTRAINT [PK_FicheiroConteudo] PRIMARY KEY CLUSTERED ([FicheiroID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



