ALTER TABLE [dbo].[FornecedorAlcance]
    ADD CONSTRAINT [PK_FornecedorAlcance] PRIMARY KEY CLUSTERED ([FornecedorID] ASC, [CondominioID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

