ALTER TABLE [dbo].[MensagemFicheiro]
    ADD CONSTRAINT [PK_MensagemFicheiro] PRIMARY KEY CLUSTERED ([MensagemFicheiroID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

