ALTER TABLE [dbo].[OpcaoPagamento]
    ADD CONSTRAINT [PK_OpcaoPagamento] PRIMARY KEY CLUSTERED ([OpcaoPagamentoID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

