ALTER TABLE [dbo].[PerfilUtilizador]
    ADD CONSTRAINT [PK_PerfilUtilizador] PRIMARY KEY CLUSTERED ([PerfilUtilizadorID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

