ALTER TABLE [dbo].[PrecoFornecedor]
    ADD CONSTRAINT [PK_PrecoFornecedor] PRIMARY KEY CLUSTERED ([PrecoFornecedorID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

