ALTER TABLE [dbo].[PrecoCondominio]
    ADD CONSTRAINT [PK_PrecoCondominio] PRIMARY KEY CLUSTERED ([PrecoCondominioID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

