/*ALTER TABLE [dbo].[PublicidadePagamento]
    ADD CONSTRAINT [PK_PublicidadePagamento] PRIMARY KEY CLUSTERED ([PublicidadePagamentoID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

