ALTER TABLE [dbo].[QuestionarioResposta]
    ADD CONSTRAINT [PK_QuestionarioResposta] PRIMARY KEY CLUSTERED ([QuestionarioRespostaID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

