ALTER TABLE [dbo].[Questionario]
    ADD CONSTRAINT [PK_Questionario] PRIMARY KEY CLUSTERED ([QuestionarioID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

