ALTER TABLE [dbo].[RecursoReserva]
    ADD CONSTRAINT [PK_RecursoReserva] PRIMARY KEY CLUSTERED ([RecursoReservaID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

