ALTER TABLE [dbo].[RecursoHorario]
    ADD CONSTRAINT [PK_RecursoHorario] PRIMARY KEY CLUSTERED ([RecursoHorarioID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

