ALTER TABLE [dbo].[TabelaLocalizada]
    ADD CONSTRAINT [PK_TabelaLocalizada] PRIMARY KEY CLUSTERED ([TabelaLocalizadaID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

