ALTER TABLE [dbo].[Veiculo]
    ADD CONSTRAINT [PK_Veiculo] PRIMARY KEY CLUSTERED ([VeiculoID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

