ALTER TABLE [dbo].[ZonaPublicidade]
    ADD CONSTRAINT [PK_ZonaPublicidade] PRIMARY KEY CLUSTERED ([ZonaPublicidadeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

