//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondoClub.Regras.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CondoClub.Regras.Resources.Mensagem", typeof(Mensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.imob.
        /// </summary>
        internal static string CondoClub {
            get {
                return ResourceManager.GetString("CondoClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portaria.
        /// </summary>
        internal static string Portaria {
            get {
                return ResourceManager.GetString("Portaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Síndico.
        /// </summary>
        internal static string Sindico {
            get {
                return ResourceManager.GetString("Sindico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Síndico.
        /// </summary>
        internal static string SindicoCondominio {
            get {
                return ResourceManager.GetString("SindicoCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas Empresas.
        /// </summary>
        internal static string TodasEmpresas {
            get {
                return ResourceManager.GetString("TodasEmpresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos Condomínios.
        /// </summary>
        internal static string TodosCondominios {
            get {
                return ResourceManager.GetString("TodosCondominios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos Moradores.
        /// </summary>
        internal static string TodosMoradores {
            get {
                return ResourceManager.GetString("TodosMoradores", resourceCulture);
            }
        }
    }
}
