//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondoClub.Regras.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notificacao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notificacao() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CondoClub.Regras.Resources.Notificacao", typeof(Notificacao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O pagamento está atrasado, agradecemos a sua regularização. No caso de já ter procedido ao pagamento não considere esta mensagem..
        /// </summary>
        internal static string AtrasoPagamento {
            get {
                return ResourceManager.GetString("AtrasoPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O pagamento está muito atrasado, em caso de não regularização o seu acesso será bloqueado..
        /// </summary>
        internal static string AvisoFinalPagamento {
            get {
                return ResourceManager.GetString("AvisoFinalPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;&lt;br/&gt;Boleto: {0}.
        /// </summary>
        internal static string AvisoPagamentoBoleto {
            get {
                return ResourceManager.GetString("AvisoPagamentoBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi adicionado um novo registo para pagamento pela utilização do X.imob - &lt;a href=&quot;{0}/Pagamento&quot; style=&quot;text-decoration: underline;&quot;&gt;pagamento&lt;/a&gt;..
        /// </summary>
        internal static string AvisoPagamentoCondominio {
            get {
                return ResourceManager.GetString("AvisoPagamentoCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi adicionado um novo registo para pagamento pela utilização do X.imob - &lt;a href=&quot;{0}/Pagamento&quot; style=&quot;text-decoration: underline;&quot;&gt;pagamento&lt;/a&gt;..
        /// </summary>
        internal static string AvisoPagamentoFornecedor {
            get {
                return ResourceManager.GetString("AvisoPagamentoFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A publicidade &quot;{0}&quot; foi aprovada.&lt;br/&gt;Foi adicionado um novo registo para pagamento - &lt;a href=&quot;{1}/Pagamento&quot; style=&quot;text-decoration: underline;&quot;&gt;pagamento&lt;/a&gt;..
        /// </summary>
        internal static string AvisoPagamentoPublicidade {
            get {
                return ResourceManager.GetString("AvisoPagamentoPublicidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sejam bem-vindos ao &lt;strong&gt;X.imob&lt;/strong&gt;, esperamos que a vossa estadia seja a mais agradável possível! &lt;br/&gt;&lt;br/&gt;Para qualquer dúvida não hesite em nos contactar através do email de apoio &lt;a href=&quot;mailto:{0}&quot; style=&quot;text-decoration: underline;&quot;&gt;{0}&lt;/a&gt;..
        /// </summary>
        internal static string ComunicadoCondominioActivo {
            get {
                return ResourceManager.GetString("ComunicadoCondominioActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O fornecedor &lt;a href=&quot;Servico/Fornecedor/{0}&quot; style=&quot;text-decoration: underline;&quot;&gt;{0}&lt;/a&gt; já está presente no X.imob.&lt;br/&gt;&quot;{1}&quot;.
        /// </summary>
        internal static string ComunicadoFornecedorActivo {
            get {
                return ResourceManager.GetString("ComunicadoFornecedorActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O fornecedor &lt;a href=&quot;Servico/Fornecedor/{0}&quot; style=&quot;text-decoration: underline;&quot;&gt;{0}&lt;/a&gt; disponibilizou uma nova promoção.&lt;br/&gt;&quot;{1}&quot;.
        /// </summary>
        internal static string ComunicadoPublicidadeActiva {
            get {
                return ResourceManager.GetString("ComunicadoPublicidadeActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;&lt;a style=&quot;text-decoration: underline;&quot; target=&quot;_blank&quot; href=&quot;{0}/Pagamento/ImprimirBoleto/{1}&quot;&gt;Imprimir Boleto&lt;/a&gt;.
        /// </summary>
        internal static string ImprimirBoleto {
            get {
                return ResourceManager.GetString("ImprimirBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devido a pagamentos em atraso o seu acesso foi bloqueado. Contacte o suporte técnico &lt;a href=&quot;mailto:{0}&quot; style=&quot;text-decoration: underline;&quot;&gt;{0}&lt;/a&gt;..
        /// </summary>
        internal static string Inactivacao {
            get {
                return ResourceManager.GetString("Inactivacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi inserido o registo &quot;{0}&quot; nos contatos..
        /// </summary>
        internal static string NovaAgenda {
            get {
                return ResourceManager.GetString("NovaAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registou-se a administradora &quot;{0}&quot; que precisa da sua aprovação..
        /// </summary>
        internal static string NovaEmpresa {
            get {
                return ResourceManager.GetString("NovaEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem uma nova mensagem no X.imob.
        /// </summary>
        internal static string NovaMensagem {
            get {
                return ResourceManager.GetString("NovaMensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recebeu uma nova mensagem de &quot;{0}&quot;:.
        /// </summary>
        internal static string NovaMensagemTexto {
            get {
                return ResourceManager.GetString("NovaMensagemTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O fornecedor &quot;{0}&quot; criou a publicidade &quot;{1}&quot; que precisa da sua aprovação..
        /// </summary>
        internal static string NovaPublicidade {
            get {
                return ResourceManager.GetString("NovaPublicidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A publicidade &quot;{0}&quot; já está activa e a ser mostrada em todos os condomínios abrangidos..
        /// </summary>
        internal static string NovaPublicidadeActiva {
            get {
                return ResourceManager.GetString("NovaPublicidadeActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sua reserva foi aprovada. {0}.
        /// </summary>
        internal static string NovaReservaAprovada {
            get {
                return ResourceManager.GetString("NovaReservaAprovada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi efectuada uma nova reserva no condomínio {0} que precisa da sua aprovação - &lt;a href=&quot;Calendario/Reserva/{1}&quot; style=&quot;text-decoration: underline;&quot;&gt;{2} em {3}&lt;/a&gt;..
        /// </summary>
        internal static string NovaReservaRecurso {
            get {
                return ResourceManager.GetString("NovaReservaRecurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sua reserva NÃO foi aprovada.&lt;br/&gt;{0}. &lt;br/&gt;Contacte o administrador para mais informações..
        /// </summary>
        internal static string NovaReservaReprovada {
            get {
                return ResourceManager.GetString("NovaReservaReprovada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registou-se o condomínio &quot;{0}&quot; que precisa da sua aprovação..
        /// </summary>
        internal static string NovoCondominio {
            get {
                return ResourceManager.GetString("NovoCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi adicionado o ficheiro &lt;a href=&quot;Ficheiro/Other/{0}&quot; style=&quot;text-decoration: underline;&quot;&gt;{1}&lt;/a&gt; à pasta &quot;{2}&quot; do arquivo..
        /// </summary>
        internal static string NovoFicheiro {
            get {
                return ResourceManager.GetString("NovoFicheiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi adicionado o ficheiro &lt;a href=&quot;Ficheiro/Other/{0}&quot; style=&quot;text-decoration: underline;&quot;&gt;{1}&lt;/a&gt; ao arquivo..
        /// </summary>
        internal static string NovoFicheiroRaiz {
            get {
                return ResourceManager.GetString("NovoFicheiroRaiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registou-se o fornecedor &quot;{0}&quot; que precisa da sua aprovação..
        /// </summary>
        internal static string NovoFornecedor {
            get {
                return ResourceManager.GetString("NovoFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi inserido o novo funcionário &quot;{0}&quot;, a sua função será &quot;{1}&quot; e o seu horário de trabalho &quot;{2}&quot;..
        /// </summary>
        internal static string NovoFuncionario {
            get {
                return ResourceManager.GetString("NovoFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gostaríamos de dar as boas-vindas a &quot;{0}&quot;, novo morador do &quot;{1}&quot;.
        /// </summary>
        internal static string NovoMorador {
            get {
                return ResourceManager.GetString("NovoMorador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi inserido um novo questionário &quot;{0}&quot;, disponível de {1} até {2}.
        /// </summary>
        internal static string NovoQuestionario {
            get {
                return ResourceManager.GetString("NovoQuestionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O seu registo foi aprovado.&lt;br/&gt;&lt;br/&gt;Sejam bem-vindos ao &lt;strong&gt;X.imob&lt;/strong&gt;, esperamos que a vossa estadia seja a mais agradável possível! .
        /// </summary>
        internal static string NovoRegistoActivo {
            get {
                return ResourceManager.GetString("NovoRegistoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi inserido um novo automóvel com a matrícula &quot;{0}&quot;, pertencente ao {1}..
        /// </summary>
        internal static string NovoVeiculo {
            get {
                return ResourceManager.GetString("NovoVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de Pagamento da subscrição do X.imob.
        /// </summary>
        internal static string PagamentoCondominioEfectuado {
            get {
                return ResourceManager.GetString("PagamentoCondominioEfectuado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O pagamento da subscrição do condominio &quot;{0}&quot; no período de &quot;{1}&quot; a &quot;{2}&quot; foi efetuado com sucesso..
        /// </summary>
        internal static string PagamentoCondominioEfectuadoTexto {
            get {
                return ResourceManager.GetString("PagamentoCondominioEfectuadoTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de Pagamento da subscrição do X.imob.
        /// </summary>
        internal static string PagamentoFornecedorEfectuado {
            get {
                return ResourceManager.GetString("PagamentoFornecedorEfectuado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O pagamento da subscrição do fornecedor &quot;{0}&quot; no período de &quot;{1}&quot; a &quot;{2}&quot; foi efetuado com sucesso..
        /// </summary>
        internal static string PagamentoFornecedorEfectuadoTexto {
            get {
                return ResourceManager.GetString("PagamentoFornecedorEfectuadoTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de Pagamento de Publicidade.
        /// </summary>
        internal static string PagamentoPublicidadeEfectuado {
            get {
                return ResourceManager.GetString("PagamentoPublicidadeEfectuado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O pagamento da publicidade &quot;{0}&quot; foi efetuado com sucesso..
        /// </summary>
        internal static string PagamentoPublicidadeEfectuadoTexto {
            get {
                return ResourceManager.GetString("PagamentoPublicidadeEfectuadoTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sua reserva foi cancelada. {0}.
        /// </summary>
        internal static string ReservaCancelada {
            get {
                return ResourceManager.GetString("ReservaCancelada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver mensagem no X.imob.
        /// </summary>
        internal static string VerMensagem {
            get {
                return ResourceManager.GetString("VerMensagem", resourceCulture);
            }
        }
    }
}
