//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondoClub.ProxyPagamento.BoletoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ccbbproxy.azurewebsites.net/", ConfigurationName="BoletoServiceReference.ProxySoap")]
    public interface ProxySoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ccbbproxy.azurewebsites.net/GerarBoleto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableServiceEntity))]
        CondoClub.ProxyPagamento.BoletoServiceReference.RetornoModel GerarBoleto(CondoClub.ProxyPagamento.BoletoServiceReference.BoletoModel boleto, CondoClub.ProxyPagamento.BoletoServiceReference.CedenteModel cedente, CondoClub.ProxyPagamento.BoletoServiceReference.SacadoModel sacado, CondoClub.ProxyPagamento.BoletoServiceReference.InstrucaoModel[] instrucoes, string MerchantKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ccbbproxy.azurewebsites.net/GetBoleto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableServiceEntity))]
        string GetBoleto(string ID, string MerchantKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ccbbproxy.azurewebsites.net/GetLinhaDigitavel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableServiceEntity))]
        string GetLinhaDigitavel(string ID, string MerchantKey);
        
        // CODEGEN: Parameter 'BoletoPagoResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="https://ccbbproxy.azurewebsites.net/BoletoPago", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableServiceEntity))]
        CondoClub.ProxyPagamento.BoletoServiceReference.BoletoPagoResponse BoletoPago(CondoClub.ProxyPagamento.BoletoServiceReference.BoletoPagoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ccbbproxy.azurewebsites.net/")]
    public partial class BoletoModel : EntidadeModel {
        
        private string vencimentoField;
        
        private string valorBoletoField;
        
        private string carteiraField;
        
        private string nossoNumeroField;
        
        private string numeroDocumentoField;
        
        private string valorCobradoField;
        
        private string cedenteIdField;
        
        private string sacadoIdField;
        
        private string especieDocumentoField;
        
        private string dataEmissaoField;
        
        private bool pagoField;
        
        private string dataPagoField;
        
        private string linhaDigitavelField;
        
        private bool remessaField;
        
        private System.DateTime dataVencField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Vencimento {
            get {
                return this.vencimentoField;
            }
            set {
                this.vencimentoField = value;
                this.RaisePropertyChanged("Vencimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ValorBoleto {
            get {
                return this.valorBoletoField;
            }
            set {
                this.valorBoletoField = value;
                this.RaisePropertyChanged("ValorBoleto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Carteira {
            get {
                return this.carteiraField;
            }
            set {
                this.carteiraField = value;
                this.RaisePropertyChanged("Carteira");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NossoNumero {
            get {
                return this.nossoNumeroField;
            }
            set {
                this.nossoNumeroField = value;
                this.RaisePropertyChanged("NossoNumero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NumeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("NumeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ValorCobrado {
            get {
                return this.valorCobradoField;
            }
            set {
                this.valorCobradoField = value;
                this.RaisePropertyChanged("ValorCobrado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CedenteId {
            get {
                return this.cedenteIdField;
            }
            set {
                this.cedenteIdField = value;
                this.RaisePropertyChanged("CedenteId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SacadoId {
            get {
                return this.sacadoIdField;
            }
            set {
                this.sacadoIdField = value;
                this.RaisePropertyChanged("SacadoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string EspecieDocumento {
            get {
                return this.especieDocumentoField;
            }
            set {
                this.especieDocumentoField = value;
                this.RaisePropertyChanged("EspecieDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DataEmissao {
            get {
                return this.dataEmissaoField;
            }
            set {
                this.dataEmissaoField = value;
                this.RaisePropertyChanged("DataEmissao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool Pago {
            get {
                return this.pagoField;
            }
            set {
                this.pagoField = value;
                this.RaisePropertyChanged("Pago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string DataPago {
            get {
                return this.dataPagoField;
            }
            set {
                this.dataPagoField = value;
                this.RaisePropertyChanged("DataPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string LinhaDigitavel {
            get {
                return this.linhaDigitavelField;
            }
            set {
                this.linhaDigitavelField = value;
                this.RaisePropertyChanged("LinhaDigitavel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool Remessa {
            get {
                return this.remessaField;
            }
            set {
                this.remessaField = value;
                this.RaisePropertyChanged("Remessa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public System.DateTime DataVenc {
            get {
                return this.dataVencField;
            }
            set {
                this.dataVencField = value;
                this.RaisePropertyChanged("DataVenc");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CedenteModel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SacadoModel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstrucaoModel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BoletoModel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ccbbproxy.azurewebsites.net/")]
    public partial class EntidadeModel : TableServiceEntity {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntidadeModel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CedenteModel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SacadoModel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstrucaoModel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BoletoModel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ccbbproxy.azurewebsites.net/")]
    public abstract partial class TableServiceEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime timestampField;
        
        private string partitionKeyField;
        
        private string rowKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PartitionKey {
            get {
                return this.partitionKeyField;
            }
            set {
                this.partitionKeyField = value;
                this.RaisePropertyChanged("PartitionKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RowKey {
            get {
                return this.rowKeyField;
            }
            set {
                this.rowKeyField = value;
                this.RaisePropertyChanged("RowKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ccbbproxy.azurewebsites.net/")]
    public partial class RetornoModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string htmlBoletoField;
        
        private string linhaDigitavelField;
        
        private string[] excecoesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HtmlBoleto {
            get {
                return this.htmlBoletoField;
            }
            set {
                this.htmlBoletoField = value;
                this.RaisePropertyChanged("HtmlBoleto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LinhaDigitavel {
            get {
                return this.linhaDigitavelField;
            }
            set {
                this.linhaDigitavelField = value;
                this.RaisePropertyChanged("LinhaDigitavel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public string[] Excecoes {
            get {
                return this.excecoesField;
            }
            set {
                this.excecoesField = value;
                this.RaisePropertyChanged("Excecoes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ccbbproxy.azurewebsites.net/")]
    public partial class CedenteModel : EntidadeModel {
        
        private string agenciaField;
        
        private string contaField;
        
        private string codigoCedenteField;
        
        private string cPFCNPJField;
        
        private string nomeField;
        
        private string convenioField;
        
        private string logradouroField;
        
        private string numeroField;
        
        private string complementoField;
        
        private string bairroField;
        
        private string cidadeField;
        
        private string cEPField;
        
        private string ufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Agencia {
            get {
                return this.agenciaField;
            }
            set {
                this.agenciaField = value;
                this.RaisePropertyChanged("Agencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Conta {
            get {
                return this.contaField;
            }
            set {
                this.contaField = value;
                this.RaisePropertyChanged("Conta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CodigoCedente {
            get {
                return this.codigoCedenteField;
            }
            set {
                this.codigoCedenteField = value;
                this.RaisePropertyChanged("CodigoCedente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CPFCNPJ {
            get {
                return this.cPFCNPJField;
            }
            set {
                this.cPFCNPJField = value;
                this.RaisePropertyChanged("CPFCNPJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Convenio {
            get {
                return this.convenioField;
            }
            set {
                this.convenioField = value;
                this.RaisePropertyChanged("Convenio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
                this.RaisePropertyChanged("Logradouro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("Numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
                this.RaisePropertyChanged("Complemento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
                this.RaisePropertyChanged("Bairro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
                this.RaisePropertyChanged("Cidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CEP {
            get {
                return this.cEPField;
            }
            set {
                this.cEPField = value;
                this.RaisePropertyChanged("CEP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
                this.RaisePropertyChanged("UF");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ccbbproxy.azurewebsites.net/")]
    public partial class SacadoModel : EntidadeModel {
        
        private string cPFCNPJField;
        
        private string nomeField;
        
        private string logradouroField;
        
        private string numeroField;
        
        private string complementoField;
        
        private string bairroField;
        
        private string cidadeField;
        
        private string cEPField;
        
        private string ufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CPFCNPJ {
            get {
                return this.cPFCNPJField;
            }
            set {
                this.cPFCNPJField = value;
                this.RaisePropertyChanged("CPFCNPJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
                this.RaisePropertyChanged("Logradouro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("Numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
                this.RaisePropertyChanged("Complemento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
                this.RaisePropertyChanged("Bairro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
                this.RaisePropertyChanged("Cidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CEP {
            get {
                return this.cEPField;
            }
            set {
                this.cEPField = value;
                this.RaisePropertyChanged("CEP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
                this.RaisePropertyChanged("UF");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ccbbproxy.azurewebsites.net/")]
    public partial class InstrucaoModel : EntidadeModel {
        
        private string codigoField;
        
        private string nDiasField;
        
        private string boletoIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NDias {
            get {
                return this.nDiasField;
            }
            set {
                this.nDiasField = value;
                this.RaisePropertyChanged("NDias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BoletoId {
            get {
                return this.boletoIdField;
            }
            set {
                this.boletoIdField = value;
                this.RaisePropertyChanged("BoletoId");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BoletoPago", WrapperNamespace="https://ccbbproxy.azurewebsites.net/", IsWrapped=true)]
    public partial class BoletoPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ccbbproxy.azurewebsites.net/", Order=0)]
        public string ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ccbbproxy.azurewebsites.net/", Order=1)]
        public string LinhaDigitavel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ccbbproxy.azurewebsites.net/", Order=2)]
        public string MerchantKey;
        
        public BoletoPagoRequest() {
        }
        
        public BoletoPagoRequest(string ID, string LinhaDigitavel, string MerchantKey) {
            this.ID = ID;
            this.LinhaDigitavel = LinhaDigitavel;
            this.MerchantKey = MerchantKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BoletoPagoResponse", WrapperNamespace="https://ccbbproxy.azurewebsites.net/", IsWrapped=true)]
    public partial class BoletoPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ccbbproxy.azurewebsites.net/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> BoletoPagoResult;
        
        public BoletoPagoResponse() {
        }
        
        public BoletoPagoResponse(System.Nullable<bool> BoletoPagoResult) {
            this.BoletoPagoResult = BoletoPagoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProxySoapChannel : CondoClub.ProxyPagamento.BoletoServiceReference.ProxySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProxySoapClient : System.ServiceModel.ClientBase<CondoClub.ProxyPagamento.BoletoServiceReference.ProxySoap>, CondoClub.ProxyPagamento.BoletoServiceReference.ProxySoap {
        
        public ProxySoapClient() {
        }
        
        public ProxySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProxySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CondoClub.ProxyPagamento.BoletoServiceReference.RetornoModel GerarBoleto(CondoClub.ProxyPagamento.BoletoServiceReference.BoletoModel boleto, CondoClub.ProxyPagamento.BoletoServiceReference.CedenteModel cedente, CondoClub.ProxyPagamento.BoletoServiceReference.SacadoModel sacado, CondoClub.ProxyPagamento.BoletoServiceReference.InstrucaoModel[] instrucoes, string MerchantKey) {
            return base.Channel.GerarBoleto(boleto, cedente, sacado, instrucoes, MerchantKey);
        }
        
        public string GetBoleto(string ID, string MerchantKey) {
            return base.Channel.GetBoleto(ID, MerchantKey);
        }
        
        public string GetLinhaDigitavel(string ID, string MerchantKey) {
            return base.Channel.GetLinhaDigitavel(ID, MerchantKey);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CondoClub.ProxyPagamento.BoletoServiceReference.BoletoPagoResponse CondoClub.ProxyPagamento.BoletoServiceReference.ProxySoap.BoletoPago(CondoClub.ProxyPagamento.BoletoServiceReference.BoletoPagoRequest request) {
            return base.Channel.BoletoPago(request);
        }
        
        public System.Nullable<bool> BoletoPago(string ID, string LinhaDigitavel, string MerchantKey) {
            CondoClub.ProxyPagamento.BoletoServiceReference.BoletoPagoRequest inValue = new CondoClub.ProxyPagamento.BoletoServiceReference.BoletoPagoRequest();
            inValue.ID = ID;
            inValue.LinhaDigitavel = LinhaDigitavel;
            inValue.MerchantKey = MerchantKey;
            CondoClub.ProxyPagamento.BoletoServiceReference.BoletoPagoResponse retVal = ((CondoClub.ProxyPagamento.BoletoServiceReference.ProxySoap)(this)).BoletoPago(inValue);
            return retVal.BoletoPagoResult;
        }
    }
}
