//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Calendario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Calendario() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CondoClub.Web.Resources.Calendario", typeof(Calendario).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        public static string Anterior {
            get {
                return ResourceManager.GetString("Anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completo.
        /// </summary>
        public static string Completo {
            get {
                return ResourceManager.GetString("Completo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que deseja reservar o recurso?.
        /// </summary>
        public static string ConfirmacaoReserva {
            get {
                return ResourceManager.GetString("ConfirmacaoReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que deseja aprovar a reserva?.
        /// </summary>
        public static string ConfirmarAprovarReserva {
            get {
                return ResourceManager.GetString("ConfirmarAprovarReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que deseja rejeitar a reserva?.
        /// </summary>
        public static string ConfirmarCancelarAprovacao {
            get {
                return ResourceManager.GetString("ConfirmarCancelarAprovacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que deseja cancelar a reserva?.
        /// </summary>
        public static string ConfirmarCancelarReserva {
            get {
                return ResourceManager.GetString("ConfirmarCancelarReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string De {
            get {
                return ResourceManager.GetString("De", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domingo.
        /// </summary>
        public static string DiaSemana1 {
            get {
                return ResourceManager.GetString("DiaSemana1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segunda.
        /// </summary>
        public static string DiaSemana2 {
            get {
                return ResourceManager.GetString("DiaSemana2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terça.
        /// </summary>
        public static string DiaSemana3 {
            get {
                return ResourceManager.GetString("DiaSemana3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarta.
        /// </summary>
        public static string DiaSemana4 {
            get {
                return ResourceManager.GetString("DiaSemana4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quinta.
        /// </summary>
        public static string DiaSemana5 {
            get {
                return ResourceManager.GetString("DiaSemana5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexta.
        /// </summary>
        public static string DiaSemana6 {
            get {
                return ResourceManager.GetString("DiaSemana6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sábado.
        /// </summary>
        public static string DiaSemana7 {
            get {
                return ResourceManager.GetString("DiaSemana7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dom..
        /// </summary>
        public static string Domigo {
            get {
                return ResourceManager.GetString("Domigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível reservar o recurso, porque são necessários {0} dias para aprovação..
        /// </summary>
        public static string ErroDiasMinimosAprovacao {
            get {
                return ResourceManager.GetString("ErroDiasMinimosAprovacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível reservar o recurso. Apenas pode reservar {0} slots num período de {1} horas..
        /// </summary>
        public static string ErroMaxSlotsReservarIntervaloReserva {
            get {
                return ResourceManager.GetString("ErroMaxSlotsReservarIntervaloReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indisponível.
        /// </summary>
        public static string Indisponivel {
            get {
                return ResourceManager.GetString("Indisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo de rejeição....
        /// </summary>
        public static string InserirMotivoCancelamento {
            get {
                return ResourceManager.GetString("InserirMotivoCancelamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legenda.
        /// </summary>
        public static string Legenda {
            get {
                return ResourceManager.GetString("Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livre.
        /// </summary>
        public static string Livre {
            get {
                return ResourceManager.GetString("Livre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to livres.
        /// </summary>
        public static string Livres {
            get {
                return ResourceManager.GetString("Livres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Janeiro.
        /// </summary>
        public static string Mes1 {
            get {
                return ResourceManager.GetString("Mes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outubro.
        /// </summary>
        public static string Mes10 {
            get {
                return ResourceManager.GetString("Mes10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novembro.
        /// </summary>
        public static string Mes11 {
            get {
                return ResourceManager.GetString("Mes11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dezembro.
        /// </summary>
        public static string Mes12 {
            get {
                return ResourceManager.GetString("Mes12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fevereiro.
        /// </summary>
        public static string Mes2 {
            get {
                return ResourceManager.GetString("Mes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Março.
        /// </summary>
        public static string Mes3 {
            get {
                return ResourceManager.GetString("Mes3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abril.
        /// </summary>
        public static string Mes4 {
            get {
                return ResourceManager.GetString("Mes4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maio.
        /// </summary>
        public static string Mes5 {
            get {
                return ResourceManager.GetString("Mes5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junho.
        /// </summary>
        public static string Mes6 {
            get {
                return ResourceManager.GetString("Mes6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julho.
        /// </summary>
        public static string Mes7 {
            get {
                return ResourceManager.GetString("Mes7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        public static string Mes8 {
            get {
                return ResourceManager.GetString("Mes8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setembro.
        /// </summary>
        public static string Mes9 {
            get {
                return ResourceManager.GetString("Mes9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próximo.
        /// </summary>
        public static string Proximo {
            get {
                return ResourceManager.GetString("Proximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qua..
        /// </summary>
        public static string Quarta {
            get {
                return ResourceManager.GetString("Quarta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quase Completo.
        /// </summary>
        public static string QuaseCompleto {
            get {
                return ResourceManager.GetString("QuaseCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qui..
        /// </summary>
        public static string Quinta {
            get {
                return ResourceManager.GetString("Quinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minhas Reservas.
        /// </summary>
        public static string Reserva {
            get {
                return ResourceManager.GetString("Reserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O recurso não pode ser reservado no dia seleccionado..
        /// </summary>
        public static string ReservaNaoDisponivelDia {
            get {
                return ResourceManager.GetString("ReservaNaoDisponivelDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sáb..
        /// </summary>
        public static string Sabado {
            get {
                return ResourceManager.GetString("Sabado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seg..
        /// </summary>
        public static string Segunda {
            get {
                return ResourceManager.GetString("Segunda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex..
        /// </summary>
        public static string Sexta {
            get {
                return ResourceManager.GetString("Sexta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ter..
        /// </summary>
        public static string Terca {
            get {
                return ResourceManager.GetString("Terca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar ao calendário.
        /// </summary>
        public static string VoltarCalendario {
            get {
                return ResourceManager.GetString("VoltarCalendario", resourceCulture);
            }
        }
    }
}
