//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Comunicado {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Comunicado() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CondoClub.Web.Resources.Comunicado", typeof(Comunicado).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Imagem.
        /// </summary>
        public static string AdicionarImagem {
            get {
                return ResourceManager.GetString("AdicionarImagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Vídeo.
        /// </summary>
        public static string AdicionarVideo {
            get {
                return ResourceManager.GetString("AdicionarVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregar mais.
        /// </summary>
        public static string CarregarMais {
            get {
                return ResourceManager.GetString("CarregarMais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentar.
        /// </summary>
        public static string Comentar {
            get {
                return ResourceManager.GetString("Comentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escreve um comentário....
        /// </summary>
        public static string Comentario {
            get {
                return ResourceManager.GetString("Comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentário(s).
        /// </summary>
        public static string Comentarios {
            get {
                return ResourceManager.GetString("Comentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desgosto.
        /// </summary>
        public static string Desgosto {
            get {
                return ResourceManager.GetString("Desgosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gosto.
        /// </summary>
        public static string Gosto {
            get {
                return ResourceManager.GetString("Gosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gosto(s).
        /// </summary>
        public static string Gostos {
            get {
                return ResourceManager.GetString("Gostos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partilha algo....
        /// </summary>
        public static string Texto {
            get {
                return ResourceManager.GetString("Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novidades.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicione o url de um vídeo do YouTube....
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
    }
}
