//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Empresa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Empresa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CondoClub.Web.Resources.Empresa", typeof(Empresa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Activo {
            get {
                return ResourceManager.GetString("Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assunto.
        /// </summary>
        public static string Assunto {
            get {
                return ResourceManager.GetString("Assunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregar mais.
        /// </summary>
        public static string CarregarMais {
            get {
                return ResourceManager.GetString("CarregarMais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Cidade {
            get {
                return ResourceManager.GetString("Cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Postal.
        /// </summary>
        public static string CodigoPostal {
            get {
                return ResourceManager.GetString("CodigoPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribuinte.
        /// </summary>
        public static string Contribuinte {
            get {
                return ResourceManager.GetString("Contribuinte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convidar administradoras.
        /// </summary>
        public static string Convite {
            get {
                return ResourceManager.GetString("Convite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CondoClub - Cadastre já sua Administradora de Condomínios.
        /// </summary>
        public static string ConviteAssuntoDefault {
            get {
                return ResourceManager.GetString("ConviteAssuntoDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezado Senhor Administrador de Condomínios&lt;br/&gt;&lt;br/&gt;Conheça o novo portal CondoClub – Sistema Integrado de Condomínios.&lt;br/&gt;&lt;a href=&apos;{0}&apos;&gt;Cadastre gratuitamente&lt;/a&gt; sua Administradora, registre todos os Condomínios sob sua gestão e passe a utilizar todas as novas funcionalidades de comunicação, armazenamento de dados e informações para facilitar suas atividades de administração.&lt;br/&gt;&lt;br/&gt;Não deixe de inserir sua Administradora numa nova era da Comunicação Digital para Condomínios.&lt;br/&gt;&lt;br/&gt;Seja Bem Vindo.&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ConviteMensagemDefault {
            get {
                return ResourceManager.GetString("ConviteMensagemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os convites foram enviados com sucesso..
        /// </summary>
        public static string ConvitesEnviados {
            get {
                return ResourceManager.GetString("ConvitesEnviados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de activação.
        /// </summary>
        public static string DataActivacao {
            get {
                return ResourceManager.GetString("DataActivacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira os emails das administradoras separados por vírgula.
        /// </summary>
        public static string Destinatarios {
            get {
                return ResourceManager.GetString("Destinatarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morada.
        /// </summary>
        public static string Endereco {
            get {
                return ResourceManager.GetString("Endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possivel activar a administradora porque não tem um utilizador associado..
        /// </summary>
        public static string ErroActivarEmpresaSemUtilizador {
            get {
                return ResourceManager.GetString("ErroActivarEmpresaSemUtilizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string EstadoRegisto {
            get {
                return ResourceManager.GetString("EstadoRegisto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        public static string Inactivo {
            get {
                return ResourceManager.GetString("Inactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidade.
        /// </summary>
        public static string Localidade {
            get {
                return ResourceManager.GetString("Localidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posição no Google Maps.
        /// </summary>
        public static string LocalizarGoogleMaps {
            get {
                return ResourceManager.GetString("LocalizarGoogleMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem.
        /// </summary>
        public static string Mensagem {
            get {
                return ResourceManager.GetString("Mensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da administradora.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar por nome, contribuinte, cidade e estado.
        /// </summary>
        public static string Pesquisar {
            get {
                return ResourceManager.GetString("Pesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por Validar.
        /// </summary>
        public static string PorValidar {
            get {
                return ResourceManager.GetString("PorValidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não tem utilizadores.
        /// </summary>
        public static string SemUtilizadores {
            get {
                return ResourceManager.GetString("SemUtilizadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas.
        /// </summary>
        public static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizadores.
        /// </summary>
        public static string Utilizadores {
            get {
                return ResourceManager.GetString("Utilizadores", resourceCulture);
            }
        }
    }
}
