//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Erro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Erro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CondoClub.Web.Resources.Erro", typeof(Erro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem de aceitar as Condições Gerais do CondoClub..
        /// </summary>
        public static string AceitarCondicoesGerais {
            get {
                return ResourceManager.GetString("AceitarCondicoesGerais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedimos desculpa mas ocorreu um erro. Neste momento não tem acesso à página, por favor contacte o administrador de sistema..
        /// </summary>
        public static string Acesso {
            get {
                return ResourceManager.GetString("Acesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome de utilizador ou password estão incorrectos..
        /// </summary>
        public static string Autenticacao {
            get {
                return ResourceManager.GetString("Autenticacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; é obrigatório..
        /// </summary>
        public static string CampoObrigatorio {
            get {
                return ResourceManager.GetString("CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Categoria já existe. Seleccione outra por favor..
        /// </summary>
        public static string CategoriaRepetida {
            get {
                return ResourceManager.GetString("CategoriaRepetida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para poder prosseguir com esta alteração terá de primeiro nomear um novo síndico..
        /// </summary>
        public static string CondominioSemSindico {
            get {
                return ResourceManager.GetString("CondominioSemSindico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os seguintes emails não têm um formato válido: {0}.
        /// </summary>
        public static string ConviteEmailsInvalidos {
            get {
                return ResourceManager.GetString("ConviteEmailsInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os seguintes emails já se encontram registados no sistema: {0}.
        /// </summary>
        public static string ConviteEmailsRepetidos {
            get {
                return ResourceManager.GetString("ConviteEmailsRepetidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os dados do registo não são válidos..
        /// </summary>
        public static string DadosIncorrectos {
            get {
                return ResourceManager.GetString("DadosIncorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve de ser maior ou igual que o campo &apos;{1}&apos;.
        /// </summary>
        public static string DataMaiorIgualQue {
            get {
                return ResourceManager.GetString("DataMaiorIgualQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve de ser maior ou igual que a data actual.
        /// </summary>
        public static string DataMaiorIgualQueHoje {
            get {
                return ResourceManager.GetString("DataMaiorIgualQueHoje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve de ser maior que o campo &apos;{1}&apos;.
        /// </summary>
        public static string DataMaiorQue {
            get {
                return ResourceManager.GetString("DataMaiorQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve de ser maior que a data actual.
        /// </summary>
        public static string DataMaiorQueHoje {
            get {
                return ResourceManager.GetString("DataMaiorQueHoje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório seleccionar uma data.
        /// </summary>
        public static string DataObrigatoria {
            get {
                return ResourceManager.GetString("DataObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Designação já existe. Seleccione outra por favor..
        /// </summary>
        public static string DesignacaoRepetida {
            get {
                return ResourceManager.GetString("DesignacaoRepetida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Email já existe. Seleccione outro por favor..
        /// </summary>
        public static string EmailRepetido {
            get {
                return ResourceManager.GetString("EmailRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível executar a operação porque este é o único utilizador da empresa..
        /// </summary>
        public static string EmpresaSemUtilizador {
            get {
                return ResourceManager.GetString("EmpresaSemUtilizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedimos desculpa mas ocorreu um erro. Neste momento não tem permissões para executar essa funcionalidade, por favor contacte o administrador de sistema..
        /// </summary>
        public static string Evento {
            get {
                return ResourceManager.GetString("Evento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ficheiro não pode ter mais de {0} mb..
        /// </summary>
        public static string FicheiroTamanhoMaximo {
            get {
                return ResourceManager.GetString("FicheiroTamanhoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve o formato de data (dd/mm/aaaa)..
        /// </summary>
        public static string FormatoData {
            get {
                return ResourceManager.GetString("FormatoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve ter o formato de email..
        /// </summary>
        public static string FormatoEmail {
            get {
                return ResourceManager.GetString("FormatoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve o formato de hora (hh:mm)..
        /// </summary>
        public static string FormatoHora {
            get {
                return ResourceManager.GetString("FormatoHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de imagem inválido..
        /// </summary>
        public static string FormatoImagemInvalido {
            get {
                return ResourceManager.GetString("FormatoImagemInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pode escolher tipos de imagem JPEG e PNG..
        /// </summary>
        public static string FormatoImagemSuportado {
            get {
                return ResourceManager.GetString("FormatoImagemSuportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve ser um número inteiro..
        /// </summary>
        public static string FormatoNumeroInteiro {
            get {
                return ResourceManager.GetString("FormatoNumeroInteiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedimos desculpa mas o fornecedor não foi encontrado..
        /// </summary>
        public static string FornecedorNaoExiste {
            get {
                return ResourceManager.GetString("FornecedorNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível executar a operação porque este é o único utilizador do fornecedor..
        /// </summary>
        public static string FornecedorSemUtilizador {
            get {
                return ResourceManager.GetString("FornecedorSemUtilizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedimos desculpa mas ocorreu um erro, por favor contacte o administrador de sistema..
        /// </summary>
        public static string Geral {
            get {
                return ResourceManager.GetString("Geral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID de ficheiro inválido..
        /// </summary>
        public static string IDFicheiroInvalido {
            get {
                return ResourceManager.GetString("IDFicheiroInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Matrícula já existe. Seleccione outra por favor..
        /// </summary>
        public static string MatriculaRepetida {
            get {
                return ResourceManager.GetString("MatriculaRepetida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione a morada no Google Maps..
        /// </summary>
        public static string MoradaGoogleMaps {
            get {
                return ResourceManager.GetString("MoradaGoogleMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome já existe. Seleccione outro por favor..
        /// </summary>
        public static string NomeRepetido {
            get {
                return ResourceManager.GetString("NomeRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve ser entre {1} e {2}..
        /// </summary>
        public static string NumeroEntre {
            get {
                return ResourceManager.GetString("NumeroEntre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve ser maior ou igual que {1}..
        /// </summary>
        public static string NumeroMaiorQue {
            get {
                return ResourceManager.GetString("NumeroMaiorQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve ser menor ou igual que {1}..
        /// </summary>
        public static string NumeroMenorQue {
            get {
                return ResourceManager.GetString("NumeroMenorQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem que seleccionar uma das opções..
        /// </summary>
        public static string OpcaoObrigatoria {
            get {
                return ResourceManager.GetString("OpcaoObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta página encontra-se em desenvolvimento..
        /// </summary>
        public static string PaginaEmDesenvolvimento {
            get {
                return ResourceManager.GetString("PaginaEmDesenvolvimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A página não foi encontrada..
        /// </summary>
        public static string PaginaNaoEncontrada {
            get {
                return ResourceManager.GetString("PaginaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Password actual não está correcta!.
        /// </summary>
        public static string PasswordActualErrada {
            get {
                return ResourceManager.GetString("PasswordActualErrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As passwords indicadas não são iguais..
        /// </summary>
        public static string PasswordsIncorrectas {
            get {
                return ResourceManager.GetString("PasswordsIncorrectas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um preço definido para os dados inseridos..
        /// </summary>
        public static string PrecoRepetidoRange {
            get {
                return ResourceManager.GetString("PrecoRepetidoRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O seu registo aguarda aprovação..
        /// </summary>
        public static string RegistoPorAprovar {
            get {
                return ResourceManager.GetString("RegistoPorAprovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro tem de indicar os destinatários dos convites..
        /// </summary>
        public static string SemDestinatarios {
            get {
                return ResourceManager.GetString("SemDestinatarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; pode ter até {1} caracteres..
        /// </summary>
        public static string TamanhoMaximo {
            get {
                return ResourceManager.GetString("TamanhoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; tem de ter pelo menos {1} caracteres..
        /// </summary>
        public static string TamanhoMinimo {
            get {
                return ResourceManager.GetString("TamanhoMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registo não pode ser eliminado porque tem dependências em outras tabelas. Contacte o administrador de sistema..
        /// </summary>
        public static string TemDependencias {
            get {
                return ResourceManager.GetString("TemDependencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upsss, ocorreu um erro :-(.
        /// </summary>
        public static string TituloErro {
            get {
                return ResourceManager.GetString("TituloErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O User Name já existe. Seleccione outro por favor..
        /// </summary>
        public static string UserNameRepetido {
            get {
                return ResourceManager.GetString("UserNameRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O utilizador não existe ou está inactivo, por favor contacte o administrador de sistema..
        /// </summary>
        public static string UtilizadorInactivo {
            get {
                return ResourceManager.GetString("UtilizadorInactivo", resourceCulture);
            }
        }
    }
}
