//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Estatistica {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Estatistica() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CondoClub.Web.Resources.Estatistica", typeof(Estatistica).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliques em Publicidade.
        /// </summary>
        public static string CliquePublicidade {
            get {
                return ResourceManager.GetString("CliquePublicidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string Empresa {
            get {
                return ResourceManager.GetString("Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erros.
        /// </summary>
        public static string Erro {
            get {
                return ResourceManager.GetString("Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim.
        /// </summary>
        public static string Fim {
            get {
                return ResourceManager.GetString("Fim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressões de Publicidade.
        /// </summary>
        public static string ImpressaoPublicidade {
            get {
                return ResourceManager.GetString("ImpressaoPublicidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novas Administradoras.
        /// </summary>
        public static string NovaAdministradora {
            get {
                return ResourceManager.GetString("NovaAdministradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novas Mensagens.
        /// </summary>
        public static string NovaMensagem {
            get {
                return ResourceManager.GetString("NovaMensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novas Publicidades.
        /// </summary>
        public static string NovaPublicidade {
            get {
                return ResourceManager.GetString("NovaPublicidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novas Reservas.
        /// </summary>
        public static string NovaReserva {
            get {
                return ResourceManager.GetString("NovaReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novos Arquivos.
        /// </summary>
        public static string NovoArquivo {
            get {
                return ResourceManager.GetString("NovoArquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novos Comunicados.
        /// </summary>
        public static string NovoComunicado {
            get {
                return ResourceManager.GetString("NovoComunicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novos Condomínios.
        /// </summary>
        public static string NovoCondominio {
            get {
                return ResourceManager.GetString("NovoCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novos Fornecedores.
        /// </summary>
        public static string NovoFornecedor {
            get {
                return ResourceManager.GetString("NovoFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novos Moradores.
        /// </summary>
        public static string NovoMorador {
            get {
                return ResourceManager.GetString("NovoMorador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novos Questionários.
        /// </summary>
        public static string NovoQuestionario {
            get {
                return ResourceManager.GetString("NovoQuestionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamento Condomínios.
        /// </summary>
        public static string PagamentoCondominio {
            get {
                return ResourceManager.GetString("PagamentoCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamento Fornecedores.
        /// </summary>
        public static string PagamentoFornecedor {
            get {
                return ResourceManager.GetString("PagamentoFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamento Publicidade.
        /// </summary>
        public static string PagamentoPublicidade {
            get {
                return ResourceManager.GetString("PagamentoPublicidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string TblCategoria {
            get {
                return ResourceManager.GetString("TblCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string TblData {
            get {
                return ResourceManager.GetString("TblData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo 1.
        /// </summary>
        public static string TblGrupo1 {
            get {
                return ResourceManager.GetString("TblGrupo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo 2.
        /// </summary>
        public static string TblGrupo2 {
            get {
                return ResourceManager.GetString("TblGrupo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TblTotal {
            get {
                return ResourceManager.GetString("TblTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string TipoEstatistica {
            get {
                return ResourceManager.GetString("TipoEstatistica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolução Diária:.
        /// </summary>
        public static string TituloGraficoEvolucao {
            get {
                return ResourceManager.GetString("TituloGraficoEvolucao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análise Individual:.
        /// </summary>
        public static string TituloGraficoPeso {
            get {
                return ResourceManager.GetString("TituloGraficoPeso", resourceCulture);
            }
        }
    }
}
