//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuFundo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuFundo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CondoClub.Web.Resources.MenuFundo", typeof(MenuFundo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central de Ajuda.
        /// </summary>
        public static string Ajuda {
            get {
                return ResourceManager.GetString("Ajuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atendimento.
        /// </summary>
        public static string Atendimento {
            get {
                return ResourceManager.GetString("Atendimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog do CondoClub.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunidade.
        /// </summary>
        public static string Comunidade {
            get {
                return ResourceManager.GetString("Comunidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CondoClub.
        /// </summary>
        public static string CondoClub {
            get {
                return ResourceManager.GetString("CondoClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conheça nossos planos.
        /// </summary>
        public static string ConhecaNossosPlanos {
            get {
                return ResourceManager.GetString("ConhecaNossosPlanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nossa equipe.
        /// </summary>
        public static string Equipa {
            get {
                return ResourceManager.GetString("Equipa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipamentos.
        /// </summary>
        public static string Equipamentos {
            get {
                return ResourceManager.GetString("Equipamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fale conosco.
        /// </summary>
        public static string FaleConosco {
            get {
                return ResourceManager.GetString("FaleConosco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortalecimento da marca.
        /// </summary>
        public static string FortalecimentoMarca {
            get {
                return ResourceManager.GetString("FortalecimentoMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicações.
        /// </summary>
        public static string Indicacoes {
            get {
                return ResourceManager.GetString("Indicacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notícias.
        /// </summary>
        public static string Noticias {
            get {
                return ResourceManager.GetString("Noticias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planos.
        /// </summary>
        public static string Planos {
            get {
                return ResourceManager.GetString("Planos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português(Brasil).
        /// </summary>
        public static string PortuguesBR {
            get {
                return ResourceManager.GetString("PortuguesBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quem somos.
        /// </summary>
        public static string QuemSomos {
            get {
                return ResourceManager.GetString("QuemSomos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacidade e termos de uso.
        /// </summary>
        public static string TermosUso {
            get {
                return ResourceManager.GetString("TermosUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour.
        /// </summary>
        public static string Tour {
            get {
                return ResourceManager.GetString("Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabalhe conosco.
        /// </summary>
        public static string TrabalheConosco {
            get {
                return ResourceManager.GetString("TrabalheConosco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
    }
}
