//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CondoClub.Web.Resources.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contatos.
        /// </summary>
        public static string Agenda {
            get {
                return ResourceManager.GetString("Agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefones úteis.
        /// </summary>
        public static string AgendaDescricao {
            get {
                return ResourceManager.GetString("AgendaDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo.
        /// </summary>
        public static string Arquivo {
            get {
                return ResourceManager.GetString("Arquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muito mais comodidade na partilha de ficheiros.
        /// </summary>
        public static string ArquivoDescricao {
            get {
                return ResourceManager.GetString("ArquivoDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendário.
        /// </summary>
        public static string Calendario {
            get {
                return ResourceManager.GetString("Calendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faça agendamentos e reservas de espaço em seu condomínio.
        /// </summary>
        public static string CalendarioDescricao {
            get {
                return ResourceManager.GetString("CalendarioDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificação.
        /// </summary>
        public static string ClassificacaoServico {
            get {
                return ResourceManager.GetString("ClassificacaoServico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ClassificacaoServicoDescricao {
            get {
                return ResourceManager.GetString("ClassificacaoServicoDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Comunicados {
            get {
                return ResourceManager.GetString("Comunicados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ComunicadosDescricao {
            get {
                return ResourceManager.GetString("ComunicadosDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condomínios.
        /// </summary>
        public static string Condominios {
            get {
                return ResourceManager.GetString("Condominios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faça a Gestão de condomínios.
        /// </summary>
        public static string CondominiosDescricao {
            get {
                return ResourceManager.GetString("CondominiosDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administradoras.
        /// </summary>
        public static string Empresas {
            get {
                return ResourceManager.GetString("Empresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faça a gestão Administradoras.
        /// </summary>
        public static string EmpresasDescricao {
            get {
                return ResourceManager.GetString("EmpresasDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatísticas.
        /// </summary>
        public static string Estatisticas {
            get {
                return ResourceManager.GetString("Estatisticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analise a utilização do Ximob.
        /// </summary>
        public static string EstatisticasDescricao {
            get {
                return ResourceManager.GetString("EstatisticasDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedores.
        /// </summary>
        public static string Fornecedores {
            get {
                return ResourceManager.GetString("Fornecedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faça a gestão de Fornecedores.
        /// </summary>
        public static string FornecedoresDescricao {
            get {
                return ResourceManager.GetString("FornecedoresDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionários.
        /// </summary>
        public static string Funcionarios {
            get {
                return ResourceManager.GetString("Funcionarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação sobre os funcionários do seu condomínio.
        /// </summary>
        public static string FuncionariosDescricao {
            get {
                return ResourceManager.GetString("FuncionariosDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string LabelMenu {
            get {
                return ResourceManager.GetString("LabelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagens.
        /// </summary>
        public static string Mensagens {
            get {
                return ResourceManager.GetString("Mensagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troque mensagens com outros condóminos.
        /// </summary>
        public static string MensagensDescricao {
            get {
                return ResourceManager.GetString("MensagensDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moradores.
        /// </summary>
        public static string Moradores {
            get {
                return ResourceManager.GetString("Moradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moradores do seu condomínio.
        /// </summary>
        public static string MoradoresDescricao {
            get {
                return ResourceManager.GetString("MoradoresDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamentos.
        /// </summary>
        public static string Pagamentos {
            get {
                return ResourceManager.GetString("Pagamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamento do seu condomínio com boleto e cartão de crédito.
        /// </summary>
        public static string PagamentosDescricao {
            get {
                return ResourceManager.GetString("PagamentosDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preços.
        /// </summary>
        public static string Precos {
            get {
                return ResourceManager.GetString("Precos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure os preços do sistema.
        /// </summary>
        public static string PrecosDescricao {
            get {
                return ResourceManager.GetString("PrecosDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicidade.
        /// </summary>
        public static string Publicidade {
            get {
                return ResourceManager.GetString("Publicidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuncie aqui.
        /// </summary>
        public static string PublicidadeDescricao {
            get {
                return ResourceManager.GetString("PublicidadeDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionários.
        /// </summary>
        public static string Questionarios {
            get {
                return ResourceManager.GetString("Questionarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        public static string QuestionariosDescricao {
            get {
                return ResourceManager.GetString("QuestionariosDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espaços Comuns.
        /// </summary>
        public static string Recursos {
            get {
                return ResourceManager.GetString("Recursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviços.
        /// </summary>
        public static string Servicos {
            get {
                return ResourceManager.GetString("Servicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviços disponíveis em sua região.
        /// </summary>
        public static string ServicosDescricao {
            get {
                return ResourceManager.GetString("ServicosDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizadores.
        /// </summary>
        public static string Utilizadores {
            get {
                return ResourceManager.GetString("Utilizadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faça a gestão de Utilizadores.
        /// </summary>
        public static string UtilizadoresDescricao {
            get {
                return ResourceManager.GetString("UtilizadoresDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veículos.
        /// </summary>
        public static string Veiculos {
            get {
                return ResourceManager.GetString("Veiculos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações sobre seus veículos.
        /// </summary>
        public static string VeiculosDescricao {
            get {
                return ResourceManager.GetString("VeiculosDescricao", resourceCulture);
            }
        }
    }
}
