//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Morador {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Morador() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CondoClub.Web.Resources.Morador", typeof(Morador).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assunto.
        /// </summary>
        public static string Assunto {
            get {
                return ResourceManager.GetString("Assunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convidar moradores.
        /// </summary>
        public static string Convite {
            get {
                return ResourceManager.GetString("Convite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CondoClub – Registe-se agora.
        /// </summary>
        public static string ConviteAssuntoDefault {
            get {
                return ResourceManager.GetString("ConviteAssuntoDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá,&lt;br/&gt;&lt;br/&gt;O seu Condomínio já está cadastrado no CondoClub, o mais novo sistema de comunicação digital para Condomínios! &lt;a href=&apos;{0}&apos;&gt;Cadastre-se já&lt;/a&gt; e comece ainda hoje a acessar as inúmeras vantagens que trazemos com exclusividade para você.&lt;br/&gt;&lt;br/&gt;Agora, morar em Condomínio ficou muito mais legal.&lt;br/&gt;&lt;br/&gt;Seja Bem Vindo.&lt;br/&gt;Equipe CondoClub.
        /// </summary>
        public static string ConviteMensagemDefault {
            get {
                return ResourceManager.GetString("ConviteMensagemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os convites foram enviados com sucesso..
        /// </summary>
        public static string ConvitesEnviados {
            get {
                return ResourceManager.GetString("ConvitesEnviados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira os emails dos moradores separados por ,.
        /// </summary>
        public static string Destinatarios {
            get {
                return ResourceManager.GetString("Destinatarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem.
        /// </summary>
        public static string Mensagem {
            get {
                return ResourceManager.GetString("Mensagem", resourceCulture);
            }
        }
    }
}
