//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pagamento {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pagamento() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CondoClub.Web.Resources.Pagamento", typeof(Pagamento).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boleto.
        /// </summary>
        public static string Boleto {
            get {
                return ResourceManager.GetString("Boleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão Crédito.
        /// </summary>
        public static string CartaoCredito {
            get {
                return ResourceManager.GetString("CartaoCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condomínio.
        /// </summary>
        public static string Condominio {
            get {
                return ResourceManager.GetString("Condominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        public static string Continuar {
            get {
                return ResourceManager.GetString("Continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Emissão.
        /// </summary>
        public static string DataEmissao {
            get {
                return ResourceManager.GetString("DataEmissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Pagamento.
        /// </summary>
        public static string DataPagamento {
            get {
                return ResourceManager.GetString("DataPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Pagamento Até.
        /// </summary>
        public static string DataPagamentoFim {
            get {
                return ResourceManager.GetString("DataPagamentoFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Pagamento De.
        /// </summary>
        public static string DataPagamentoInicio {
            get {
                return ResourceManager.GetString("DataPagamentoInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Pagamento.
        /// </summary>
        public static string EstadoPagamento {
            get {
                return ResourceManager.GetString("EstadoPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim.
        /// </summary>
        public static string Fim {
            get {
                return ResourceManager.GetString("Fim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor.
        /// </summary>
        public static string Fonecedor {
            get {
                return ResourceManager.GetString("Fonecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma Pagamento.
        /// </summary>
        public static string FormaPagamento {
            get {
                return ResourceManager.GetString("FormaPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir Boleto.
        /// </summary>
        public static string ImprimirBoleto {
            get {
                return ResourceManager.GetString("ImprimirBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcar como Pago.
        /// </summary>
        public static string MarcarPago {
            get {
                return ResourceManager.GetString("MarcarPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Pago.
        /// </summary>
        public static string NaoPago {
            get {
                return ResourceManager.GetString("NaoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao continuar será redireccionado para a página de pagamento para inserir os  dados do seu cartão..
        /// </summary>
        public static string NotaContinuar {
            get {
                return ResourceManager.GetString("NotaContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O pagamento foi efectuado com sucesso. Obrigado..
        /// </summary>
        public static string PagamentoComSucesso {
            get {
                return ResourceManager.GetString("PagamentoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamentos.
        /// </summary>
        public static string Pagamentos {
            get {
                return ResourceManager.GetString("Pagamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao efectuar o pagamento..
        /// </summary>
        public static string PagamentoSemSucesso {
            get {
                return ResourceManager.GetString("PagamentoSemSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagar.
        /// </summary>
        public static string Pagar {
            get {
                return ResourceManager.GetString("Pagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago.
        /// </summary>
        public static string Pago {
            get {
                return ResourceManager.GetString("Pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar por nome de condomínio ou nome de fornecedor.
        /// </summary>
        public static string PesquisarCondoclub {
            get {
                return ResourceManager.GetString("PesquisarCondoclub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar por nome de condomínio.
        /// </summary>
        public static string PesquisarEmpresa {
            get {
                return ResourceManager.GetString("PesquisarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referência Pagamento.
        /// </summary>
        public static string ReferenciaPagamento {
            get {
                return ResourceManager.GetString("ReferenciaPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que deseja marcar o registo como pago?.
        /// </summary>
        public static string TemCertezaMarcarPago {
            get {
                return ResourceManager.GetString("TemCertezaMarcarPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentar Novamente.
        /// </summary>
        public static string TentarNovamente {
            get {
                return ResourceManager.GetString("TentarNovamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Cartão.
        /// </summary>
        public static string TipoCartao {
            get {
                return ResourceManager.GetString("TipoCartao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amex.
        /// </summary>
        public static string TipoCartao_Amex {
            get {
                return ResourceManager.GetString("TipoCartao_Amex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aura.
        /// </summary>
        public static string TipoCartao_Aura {
            get {
                return ResourceManager.GetString("TipoCartao_Aura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diners.
        /// </summary>
        public static string TipoCartao_Diners {
            get {
                return ResourceManager.GetString("TipoCartao_Diners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string TipoCartao_Discover {
            get {
                return ResourceManager.GetString("TipoCartao_Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elo.
        /// </summary>
        public static string TipoCartao_Elo {
            get {
                return ResourceManager.GetString("TipoCartao_Elo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jcb.
        /// </summary>
        public static string TipoCartao_Jcb {
            get {
                return ResourceManager.GetString("TipoCartao_Jcb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MasterCard.
        /// </summary>
        public static string TipoCartao_MasterCard {
            get {
                return ResourceManager.GetString("TipoCartao_MasterCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa.
        /// </summary>
        public static string TipoCartao_Visa {
            get {
                return ResourceManager.GetString("TipoCartao_Visa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador Pagamento.
        /// </summary>
        public static string UtilizadorPagamento {
            get {
                return ResourceManager.GetString("UtilizadorPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
    }
}
