//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Publicidade {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Publicidade() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CondoClub.Web.Resources.Publicidade", typeof(Publicidade).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Imagem.
        /// </summary>
        public static string AdicionarImagem {
            get {
                return ResourceManager.GetString("AdicionarImagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Clique na imagem para alterar).
        /// </summary>
        public static string AlterarImagem {
            get {
                return ResourceManager.GetString("AlterarImagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovado.
        /// </summary>
        public static string Aprovado {
            get {
                return ResourceManager.GetString("Aprovado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregar Imagem.
        /// </summary>
        public static string CarregarImagem {
            get {
                return ResourceManager.GetString("CarregarImagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Aprovação.
        /// </summary>
        public static string DataAprovacao {
            get {
                return ResourceManager.GetString("DataAprovacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicar.
        /// </summary>
        public static string Duplicar {
            get {
                return ResourceManager.GetString("Duplicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para criar uma publicidade de topo é obrigatório carregar uma imagem.
        /// </summary>
        public static string ErroImagemObrigatoriaPublicidadeTopo {
            get {
                return ResourceManager.GetString("ErroImagemObrigatoriaPublicidadeTopo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para criar uma publicidade lateral é obrigatório carregar uma imagem ou preencher o texto.
        /// </summary>
        public static string ErroImagemTextoObrigatorioPublicidadeLateral {
            get {
                return ResourceManager.GetString("ErroImagemTextoObrigatorioPublicidadeLateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Fim.
        /// </summary>
        public static string Fim {
            get {
                return ResourceManager.GetString("Fim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor.
        /// </summary>
        public static string Fornecedor {
            get {
                return ResourceManager.GetString("Fornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem.
        /// </summary>
        public static string Imagem {
            get {
                return ResourceManager.GetString("Imagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Início.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Aprovado.
        /// </summary>
        public static string NaoAprovado {
            get {
                return ResourceManager.GetString("NaoAprovado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As imagens para publicidade de topo são apresentadas com o tamanho de 654px de altura por 190px de largura. As imagens para publidade lateral são apresentadas com o tamanho de 154px de altura por 154px de largura. Para garantir a qualidade da imagem, por favor, respeite estas dimensões..
        /// </summary>
        public static string NotaTamanhoImagens {
            get {
                return ResourceManager.GetString("NotaTamanhoImagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago.
        /// </summary>
        public static string Pago {
            get {
                return ResourceManager.GetString("Pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar por nome de fornecedor ou titulo de publicidade.
        /// </summary>
        public static string PesquisarNomeCondoClub {
            get {
                return ResourceManager.GetString("PesquisarNomeCondoClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar por título de publicidade.
        /// </summary>
        public static string PesquisarNomeFornecedor {
            get {
                return ResourceManager.GetString("PesquisarNomeFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço.
        /// </summary>
        public static string Preco {
            get {
                return ResourceManager.GetString("Preco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicidade.
        /// </summary>
        public static string Publicidades {
            get {
                return ResourceManager.GetString("Publicidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raio Acção (Km).
        /// </summary>
        public static string RaioAccao {
            get {
                return ResourceManager.GetString("RaioAccao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que deseja duplicar a publicidade?.
        /// </summary>
        public static string TemCertezaDuplicar {
            get {
                return ResourceManager.GetString("TemCertezaDuplicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto.
        /// </summary>
        public static string Texto {
            get {
                return ResourceManager.GetString("Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string Zona {
            get {
                return ResourceManager.GetString("Zona", resourceCulture);
            }
        }
    }
}
