//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Questionario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Questionario() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CondoClub.Web.Resources.Questionario", typeof(Questionario).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentários.
        /// </summary>
        public static string Comentario {
            get {
                return ResourceManager.GetString("Comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Descricao {
            get {
                return ResourceManager.GetString("Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim votação.
        /// </summary>
        public static string Fim {
            get {
                return ResourceManager.GetString("Fim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início votação.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de .
        /// </summary>
        public static string Legenda1 {
            get {
                return ResourceManager.GetString("Legenda1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  votos .
        /// </summary>
        public static string Legenda2 {
            get {
                return ResourceManager.GetString("Legenda2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  desde .
        /// </summary>
        public static string Legenda3 {
            get {
                return ResourceManager.GetString("Legenda3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  até .
        /// </summary>
        public static string Legenda4 {
            get {
                return ResourceManager.GetString("Legenda4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção 1.
        /// </summary>
        public static string Opcao1 {
            get {
                return ResourceManager.GetString("Opcao1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção 2.
        /// </summary>
        public static string Opcao2 {
            get {
                return ResourceManager.GetString("Opcao2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção 3.
        /// </summary>
        public static string Opcao3 {
            get {
                return ResourceManager.GetString("Opcao3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção 4.
        /// </summary>
        public static string Opcao4 {
            get {
                return ResourceManager.GetString("Opcao4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção 5.
        /// </summary>
        public static string Opcao5 {
            get {
                return ResourceManager.GetString("Opcao5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção 6.
        /// </summary>
        public static string Opcao6 {
            get {
                return ResourceManager.GetString("Opcao6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção 7.
        /// </summary>
        public static string Opcao7 {
            get {
                return ResourceManager.GetString("Opcao7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção 8.
        /// </summary>
        public static string Opcao8 {
            get {
                return ResourceManager.GetString("Opcao8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção seleccionada.
        /// </summary>
        public static string OpcaoSeleccionada {
            get {
                return ResourceManager.GetString("OpcaoSeleccionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opções.
        /// </summary>
        public static string Opcoes {
            get {
                return ResourceManager.GetString("Opcoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugira outra opção ou deixe um comentário....
        /// </summary>
        public static string OutraOpcao {
            get {
                return ResourceManager.GetString("OutraOpcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questão.
        /// </summary>
        public static string Questao {
            get {
                return ResourceManager.GetString("Questao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado.
        /// </summary>
        public static string Resultado {
            get {
                return ResourceManager.GetString("Resultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votar.
        /// </summary>
        public static string Votar {
            get {
                return ResourceManager.GetString("Votar", resourceCulture);
            }
        }
    }
}
