//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recurso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recurso() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CondoClub.Web.Resources.Recurso", typeof(Recurso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Activo {
            get {
                return ResourceManager.GetString("Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Horário.
        /// </summary>
        public static string AdicionarHorario {
            get {
                return ResourceManager.GetString("AdicionarHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovar.
        /// </summary>
        public static string Aprovar {
            get {
                return ResourceManager.GetString("Aprovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existem reservas para datas posteriores ao dia de hoje.\nNão vai ser possível garantir que estas reservas respeitarão as novas regras do campos Máximo de Reservas por Dia.\nTem a certeza que deseja gravar as alterações?.
        /// </summary>
        public static string AvisoMaxSlotsReservaIntervaloReserva {
            get {
                return ResourceManager.GetString("AvisoMaxSlotsReservaIntervaloReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas as reservas existentes nesse período serão canceladas.\nTem a certeza que deseja efectuar as alterações?.
        /// </summary>
        public static string AvisoTodasReservasCanceladas {
            get {
                return ResourceManager.GetString("AvisoTodasReservasCanceladas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejeitar.
        /// </summary>
        public static string CancelarAprovacao {
            get {
                return ResourceManager.GetString("CancelarAprovacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string CancelarReserva {
            get {
                return ResourceManager.GetString("CancelarReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar.
        /// </summary>
        public static string Configurar {
            get {
                return ResourceManager.GetString("Configurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Fim.
        /// </summary>
        public static string DataFim {
            get {
                return ResourceManager.GetString("DataFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Início.
        /// </summary>
        public static string DataInicio {
            get {
                return ResourceManager.GetString("DataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designação.
        /// </summary>
        public static string Designacao {
            get {
                return ResourceManager.GetString("Designacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia da Semana.
        /// </summary>
        public static string DiaSemana {
            get {
                return ResourceManager.GetString("DiaSemana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dias mínimos para aprovação.
        /// </summary>
        public static string DiasMinimosAprovacao {
            get {
                return ResourceManager.GetString("DiasMinimosAprovacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº de dias de antecedência necessários para se solicitar a reserva..
        /// </summary>
        public static string DiasMinimosAprovacaoInfo {
            get {
                return ResourceManager.GetString("DiasMinimosAprovacaoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponível.
        /// </summary>
        public static string Disponivel {
            get {
                return ResourceManager.GetString("Disponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duração Slot (minutos).
        /// </summary>
        public static string DuracaoSlot {
            get {
                return ResourceManager.GetString("DuracaoSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período de tempo de cada reserva em minutos. Os períodos de reserva não poderão ultrapassar a meia noite do dia, ou a soma dos períodos perfazer mais de 24h..
        /// </summary>
        public static string DuracaoSlotInfo {
            get {
                return ResourceManager.GetString("DuracaoSlotInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao  gravar novo registo porque colide com outro horário no mesmo dia..
        /// </summary>
        public static string ErroColisaoSlots {
            get {
                return ResourceManager.GetString("ErroColisaoSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível apagar essa Área Comum porque possui reservas associadas no Sistema.
        /// </summary>
        public static string ErroRecursoComReservas {
            get {
                return ResourceManager.GetString("ErroRecursoComReservas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A combinação Hora Inicio, Numero Slots e Duração de Slot não é válida porque ultrapassa as 24 horas..
        /// </summary>
        public static string ErroSuperior24Horas {
            get {
                return ResourceManager.GetString("ErroSuperior24Horas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado da Reserva.
        /// </summary>
        public static string EstadoReserva {
            get {
                return ResourceManager.GetString("EstadoReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendente de Confirmação.
        /// </summary>
        public static string EstadoReservaPendenteAprovacao {
            get {
                return ResourceManager.GetString("EstadoReservaPendenteAprovacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Aprovado.
        /// </summary>
        public static string EstadoReservaReprovado {
            get {
                return ResourceManager.GetString("EstadoReservaReprovado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservado.
        /// </summary>
        public static string EstadoReservaReservado {
            get {
                return ResourceManager.GetString("EstadoReservaReservado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Início.
        /// </summary>
        public static string HoraInicio {
            get {
                return ResourceManager.GetString("HoraInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horário.
        /// </summary>
        public static string Horario {
            get {
                return ResourceManager.GetString("Horario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure os horários por cada dia da semana. Poderá acrescentar mais do que 1 horário por dia..
        /// </summary>
        public static string HorarioInfo {
            get {
                return ResourceManager.GetString("HorarioInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora a partir da qual está disponível para reserva (formato HH:MM).
        /// </summary>
        public static string InicioInfo {
            get {
                return ResourceManager.GetString("InicioInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervalo de reserva (horas).
        /// </summary>
        public static string IntervaloReserva {
            get {
                return ResourceManager.GetString("IntervaloReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervalo, em horas, para limitar o número máximo de reservas.
        /// </summary>
        public static string IntervaloReservaInfo {
            get {
                return ResourceManager.GetString("IntervaloReservaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Reservas.
        /// </summary>
        public static string ListaReservas {
            get {
                return ResourceManager.GetString("ListaReservas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo de Reservas por Dia.
        /// </summary>
        public static string MaxSlotsReserva {
            get {
                return ResourceManager.GetString("MaxSlotsReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número máximo de reservas, de um morador, por dia.
        /// </summary>
        public static string MaxSlotsReservaInfo {
            get {
                return ResourceManager.GetString("MaxSlotsReservaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morador.
        /// </summary>
        public static string Morador {
            get {
                return ResourceManager.GetString("Morador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Disponível.
        /// </summary>
        public static string NaoDisponivel {
            get {
                return ResourceManager.GetString("NaoDisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº. de Reservas (Slots).
        /// </summary>
        public static string NumeroSlots {
            get {
                return ResourceManager.GetString("NumeroSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº de períodos de reserva possíveis de se requisitar em 24h.
        /// </summary>
        public static string NumeroSlotsInfo {
            get {
                return ResourceManager.GetString("NumeroSlotsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguarda Confirmação.
        /// </summary>
        public static string PendenteAprovacao {
            get {
                return ResourceManager.GetString("PendenteAprovacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espaços Comuns.
        /// </summary>
        public static string Recursos {
            get {
                return ResourceManager.GetString("Recursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requer Aprovação pelo Síndico.
        /// </summary>
        public static string RequerAprovacao {
            get {
                return ResourceManager.GetString("RequerAprovacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessária a aprovação pelo síndico para utilização?.
        /// </summary>
        public static string RequerAprovacaoInfo {
            get {
                return ResourceManager.GetString("RequerAprovacaoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservado.
        /// </summary>
        public static string Reservado {
            get {
                return ResourceManager.GetString("Reservado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar Reserva.
        /// </summary>
        public static string Reservar {
            get {
                return ResourceManager.GetString("Reservar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservas.
        /// </summary>
        public static string Reservas {
            get {
                return ResourceManager.GetString("Reservas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas as reservas neste periodo serão canceladas.\nTem a certeza que deseja apagar o registo?.
        /// </summary>
        public static string TemCertezaApagarReservasSeraoCanceladas {
            get {
                return ResourceManager.GetString("TemCertezaApagarReservasSeraoCanceladas", resourceCulture);
            }
        }
    }
}
