//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Registo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Registo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CondoClub.Web.Resources.Registo", typeof(Registo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Li e aceito as Condições Gerais do X.imob (&lt;a href=&quot;{0}&quot; target=&quot;_blank&quot; class=&quot;link-orange&quot;&gt;clique aqui para consultar&lt;/a&gt;)&lt;/label&gt;.
        /// </summary>
        public static string AceitarCondicoesGerais {
            get {
                return ResourceManager.GetString("AceitarCondicoesGerais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione todas as categorias do seu negócio.
        /// </summary>
        public static string AdicioneCategoria {
            get {
                return ResourceManager.GetString("AdicioneCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Clique na imagem para alterar).
        /// </summary>
        public static string AlterarAvatar {
            get {
                return ResourceManager.GetString("AlterarAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluir registo.
        /// </summary>
        public static string ConcluirRegisto {
            get {
                return ResourceManager.GetString("ConcluirRegisto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O &lt;b&gt;Ximob.com.br&lt;/b&gt; é um serviço interativo oferecido a Condomínios por meio de página eletrônica na internet que oferece possibilidades de interatividade entre Administradoras, Síndicos e Condôminos, bem como postagem de arquivos, informações, acesso a prestadores de serviços, e-commerce entre outros serviços, a partir da integração de diversas fontes de informação. O acesso ao &lt;b&gt;Ximob.com.br&lt;/b&gt; representa a aceitação expressa e irrestrita dos termos de uso abaixo descritos. Se você não concorda com os [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CondicoesGeraisMensagem {
            get {
                return ResourceManager.GetString("CondicoesGeraisMensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;i&gt;Termos de Uso&lt;/i&gt;&lt;/b&gt;.
        /// </summary>
        public static string CondicoesGeraisTitulo {
            get {
                return ResourceManager.GetString("CondicoesGeraisTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha os campos seguintes com os dados do seu condomínio.
        /// </summary>
        public static string MensagemCondominio {
            get {
                return ResourceManager.GetString("MensagemCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha os campos seguintes com os dados da sua administradora de condomínios.
        /// </summary>
        public static string MensagemEmpresa {
            get {
                return ResourceManager.GetString("MensagemEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha os campos seguintes com os dados do seu serviço.
        /// </summary>
        public static string MensagemFornecedor {
            get {
                return ResourceManager.GetString("MensagemFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O seu registo foi concluído com êxito.&lt;br /&gt;Os dados serão revistos por um administrador e será notificado assim que o seu registo se encontre validado.&lt;br /&gt;&lt;br /&gt;Obrigado,&lt;br /&gt;Equipa X.imob.
        /// </summary>
        public static string MensagemSucesso {
            get {
                return ResourceManager.GetString("MensagemSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha os campos seguintes com os seus dados pessoais.
        /// </summary>
        public static string MensagemUtilizador {
            get {
                return ResourceManager.GetString("MensagemUtilizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registe um Condomínio.
        /// </summary>
        public static string RegisteCondominio {
            get {
                return ResourceManager.GetString("RegisteCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registe uma Administradora de Condomínios.
        /// </summary>
        public static string RegisteEmpresa {
            get {
                return ResourceManager.GetString("RegisteEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registe um Fornecedor.
        /// </summary>
        public static string RegisteFornecedor {
            get {
                return ResourceManager.GetString("RegisteFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso!.
        /// </summary>
        public static string Sucesso {
            get {
                return ResourceManager.GetString("Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar ao início.
        /// </summary>
        public static string VoltarInicio {
            get {
                return ResourceManager.GetString("VoltarInicio", resourceCulture);
            }
        }
    }
}
