//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Servico {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Servico() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CondoClub.Web.Resources.Servico", typeof(Servico).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Activo {
            get {
                return ResourceManager.GetString("Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Nova Categoria.
        /// </summary>
        public static string AdicionarCategoria {
            get {
                return ResourceManager.GetString("AdicionarCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assunto.
        /// </summary>
        public static string Assunto {
            get {
                return ResourceManager.GetString("Assunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorias.
        /// </summary>
        public static string Categorias {
            get {
                return ResourceManager.GetString("Categorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Cidade {
            get {
                return ResourceManager.GetString("Cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking Classificação.
        /// </summary>
        public static string ClassificacaoMedia {
            get {
                return ResourceManager.GetString("ClassificacaoMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem que seleccionar o número de estrelas..
        /// </summary>
        public static string ClassificacaoObrigatorio {
            get {
                return ResourceManager.GetString("ClassificacaoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Postal.
        /// </summary>
        public static string CodigoPostal {
            get {
                return ResourceManager.GetString("CodigoPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escreve um comentário....
        /// </summary>
        public static string Comentario {
            get {
                return ResourceManager.GetString("Comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentário(s).
        /// </summary>
        public static string Comentarios {
            get {
                return ResourceManager.GetString("Comentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribuinte.
        /// </summary>
        public static string Contribuinte {
            get {
                return ResourceManager.GetString("Contribuinte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convidar fornecedores.
        /// </summary>
        public static string Convite {
            get {
                return ResourceManager.GetString("Convite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CondoClub – Cadastre-se já como Fornecedor de Condomínios.
        /// </summary>
        public static string ConviteAssuntoDefault {
            get {
                return ResourceManager.GetString("ConviteAssuntoDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá, Senhor Fornecedor de Produtos e Serviços para Condomínios&lt;br/&gt;&lt;br/&gt;Conheça o novo portal CondoClub – Sistema Integrado de Condomínios.&lt;br/&gt;&lt;br/&gt;&lt;a href=&apos;{0}&apos;&gt;Cadastre já&lt;/a&gt; sua empresa fornecedora de produtos e serviços para Condomínios  e  passe a utilizar todas as novas funcionalidades de comunicação, banco de dados e informações para facilitar suas atividades de venda e de prestação de serviços.&lt;br/&gt;&lt;br/&gt;Não deixe de inserir sua empresa numa nova era da Comunicação Digital para Condomínios.&lt;br/&gt;&lt;br [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ConviteMensagemDefault {
            get {
                return ResourceManager.GetString("ConviteMensagemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os convites foram enviados com sucesso..
        /// </summary>
        public static string ConvitesEnviados {
            get {
                return ResourceManager.GetString("ConvitesEnviados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de activação.
        /// </summary>
        public static string DataActivacao {
            get {
                return ResourceManager.GetString("DataActivacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Descricao {
            get {
                return ResourceManager.GetString("Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira os emails dos fornecedores separados por vírgula.
        /// </summary>
        public static string Destinatarios {
            get {
                return ResourceManager.GetString("Destinatarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morada.
        /// </summary>
        public static string Endereco {
            get {
                return ResourceManager.GetString("Endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mensagem foi enviada com sucesso..
        /// </summary>
        public static string EnvioMensagemComSucesso {
            get {
                return ResourceManager.GetString("EnvioMensagemComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possivel activar o fornecedor porque não tem um utilizador associado..
        /// </summary>
        public static string ErroActivarFornecedorSemUtilizador {
            get {
                return ResourceManager.GetString("ErroActivarFornecedorSemUtilizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estrelas.
        /// </summary>
        public static string Estrelas {
            get {
                return ResourceManager.GetString("Estrelas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma de pagamento.
        /// </summary>
        public static string FormaPagamento {
            get {
                return ResourceManager.GetString("FormaPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        public static string Inactivo {
            get {
                return ResourceManager.GetString("Inactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Pode influenciar o valor do pagamento).
        /// </summary>
        public static string InfluenciaPreco {
            get {
                return ResourceManager.GetString("InfluenciaPreco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidade.
        /// </summary>
        public static string Localidade {
            get {
                return ResourceManager.GetString("Localidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escreve uma mensagem....
        /// </summary>
        public static string Mensagem {
            get {
                return ResourceManager.GetString("Mensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Mensagem.
        /// </summary>
        public static string NovaMensagem {
            get {
                return ResourceManager.GetString("NovaMensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção de pagamento.
        /// </summary>
        public static string OpcaoPagamento {
            get {
                return ResourceManager.GetString("OpcaoPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por Validar.
        /// </summary>
        public static string PorValidar {
            get {
                return ResourceManager.GetString("PorValidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raio de acção (km).
        /// </summary>
        public static string RaioAccao {
            get {
                return ResourceManager.GetString("RaioAccao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não tem categorias.
        /// </summary>
        public static string SemCategorias {
            get {
                return ResourceManager.GetString("SemCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sua pesquisa não devolveu resultados..
        /// </summary>
        public static string SemResultados {
            get {
                return ResourceManager.GetString("SemResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não tem utilizadores.
        /// </summary>
        public static string SemUtilizadores {
            get {
                return ResourceManager.GetString("SemUtilizadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string Telefone {
            get {
                return ResourceManager.GetString("Telefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o serviço pretendido ou o nome de fornecedor....
        /// </summary>
        public static string TermoPesquisa {
            get {
                return ResourceManager.GetString("TermoPesquisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório preenchimento do campo Mensagem..
        /// </summary>
        public static string TextoMensagemObrigatorio {
            get {
                return ResourceManager.GetString("TextoMensagemObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa de Serviços.
        /// </summary>
        public static string TituloServicos {
            get {
                return ResourceManager.GetString("TituloServicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número total de comentários.
        /// </summary>
        public static string TotalComentarios {
            get {
                return ResourceManager.GetString("TotalComentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizadores.
        /// </summary>
        public static string Utilizadores {
            get {
                return ResourceManager.GetString("Utilizadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Classificações.
        /// </summary>
        public static string VerClassificacoes {
            get {
                return ResourceManager.GetString("VerClassificacoes", resourceCulture);
            }
        }
    }
}
