//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Utilizador {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Utilizador() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CondoClub.Web.Resources.Utilizador", typeof(Utilizador).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Activo {
            get {
                return ResourceManager.GetString("Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa por nome do condomínio....
        /// </summary>
        public static string AlterarContextoPesquisa {
            get {
                return ResourceManager.GetString("AlterarContextoPesquisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Password.
        /// </summary>
        public static string AlterarPassword {
            get {
                return ResourceManager.GetString("AlterarPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condomínio.
        /// </summary>
        public static string Condominio {
            get {
                return ResourceManager.GetString("Condominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar password.
        /// </summary>
        public static string ConfirmarPassword {
            get {
                return ResourceManager.GetString("ConfirmarPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar dados pessoais.
        /// </summary>
        public static string EditarPerfil {
            get {
                return ResourceManager.GetString("EditarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administradora.
        /// </summary>
        public static string Empresa {
            get {
                return ResourceManager.GetString("Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string Entrar {
            get {
                return ResourceManager.GetString("Entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor.
        /// </summary>
        public static string Fornecedor {
            get {
                return ResourceManager.GetString("Fornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracção.
        /// </summary>
        public static string Fraccao {
            get {
                return ResourceManager.GetString("Fraccao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        public static string Inactivo {
            get {
                return ResourceManager.GetString("Inactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instituição.
        /// </summary>
        public static string NomeInstituicao {
            get {
                return ResourceManager.GetString("NomeInstituicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password atual.
        /// </summary>
        public static string PasswordActual {
            get {
                return ResourceManager.GetString("PasswordActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados pessoais.
        /// </summary>
        public static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do condomínio.
        /// </summary>
        public static string PerfilCondominio {
            get {
                return ResourceManager.GetString("PerfilCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados da empresa.
        /// </summary>
        public static string PerfilEmpresa {
            get {
                return ResourceManager.GetString("PerfilEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do fornecedor.
        /// </summary>
        public static string PerfilFornecedor {
            get {
                return ResourceManager.GetString("PerfilFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil de utilizador.
        /// </summary>
        public static string PerfilUtilizador {
            get {
                return ResourceManager.GetString("PerfilUtilizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordar autenticação.
        /// </summary>
        public static string Recordar {
            get {
                return ResourceManager.GetString("Recordar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueceu-se da password?.
        /// </summary>
        public static string RecuperarPassword {
            get {
                return ResourceManager.GetString("RecuperarPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair do condomínio.
        /// </summary>
        public static string SairCondominio {
            get {
                return ResourceManager.GetString("SairCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar condomínio.
        /// </summary>
        public static string SeleccionarCondominio {
            get {
                return ResourceManager.GetString("SeleccionarCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione um utilizador.
        /// </summary>
        public static string SeleccioneUtilizador {
            get {
                return ResourceManager.GetString("SeleccioneUtilizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não tem ainda CondoClub? Faça agora seu registo!.
        /// </summary>
        public static string SemConta {
            get {
                return ResourceManager.GetString("SemConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
